
fullnameOverride: "languages-start-points"

daemonSet: true

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: languages-start-points-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: languages-start-points
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: languages-start-points-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        memory: 64Mi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
