
fullnameOverride: "languages-start-points"

replicaCount: 3

service:
  port: 4534
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4534"

volumes:
  - name: languages-start-points-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: languages-start-points
    image: cyberdojo/languages-start-points-all
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: languages-start-points-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    livenessProbe:
      path: /alive?
      port: 4534
    readinessProbe:
      path: /ready?
      port: 4534

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
